// "use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "app/components/shared/Header";
import { Footer } from "app/components/shared/Footer";
import "app/scss/globals.scss";

// if you loading a variable font, you dont need to specify th font weight
const inter = Inter({
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "EasyFWD",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
